name: Build and Push to DockerHub

on:
  push:
    branches: [ "main" ]
  # Optional: schedule a daily or weekly rebuild
  schedule:
    - cron:  "0 1 * * *"  # runs every day at 01:00 UTC

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 17 (for building the WAR)
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build WAR
        run: mvn clean package

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORDS }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/tomcat-sample:latest \
            .

      - name: Push to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tomcat-sample:latest

